name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd /home/vistara/vistara-car-rental-backend

            git pull origin main

            npm install

            # restart safely (fixes missing process issue)
            pm2 restart vistara-car-rental-backend --update-env || \
            pm2 start npm --name "vistara-car-rental-backend" -- start

            pm2 save